import "dotenv/config";
import esbuild from "esbuild";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import process from "process";
// import builtins from 'builtin-modules'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

console.log(`esbuild version = ${esbuild.version}`);

const prod = process.argv[2] === "production";

const DEFAULT_ONEDRIVE_CLIENT_ID = process.env.ONEDRIVE_CLIENT_ID || "";
const DEFAULT_ONEDRIVE_AUTHORITY = process.env.ONEDRIVE_AUTHORITY || "";

esbuild
  .context({
    banner: {
      js: banner,
    },
    loader: {
      ".svg": "text",
    },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "fs",
      "tls",
      "net",
      "http",
      "https",
      "vm",
      "url",
      "util",
      "path",
      "stream",
      "crypto",
      "zlib",
      "child_process",
      "assert",
      "buffer",
      "os",
      "events",
      "tty",
      "node:url",
      "node:util",
      "node:path",
      "node:stream",
      "node:crypto",
      "node:zlib",
      "node:fs",
      "node:net",
      "node:http",
      "node:https",
      "node:tls",
      "node:vm",
      "node:child_process",
      "node:assert",
      "node:buffer",
      "node:os",
      "node:events",
      "node:tty",
      // "process",
      // ...builtins
    ],
    inject: ["./esbuild.injecthelper.mjs"],
    format: "cjs",
    // watch: !prod, // no longer valid in esbuild 0.17
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outfile: "main.js",
    define: {
      "global.DEFAULT_ONEDRIVE_CLIENT_ID": `"${DEFAULT_ONEDRIVE_CLIENT_ID}"`,
      "global.DEFAULT_ONEDRIVE_AUTHORITY": `"${DEFAULT_ONEDRIVE_AUTHORITY}"`,
      global: "window",
      "process.env.NODE_DEBUG": `undefined`, // ugly fix
      "process.env.DEBUG": `undefined`, // ugly fix
    },
    plugins: [inlineWorkerPlugin()],
  })
  .then((context) => {
    if (process.argv.includes("--watch")) {
      // Enable watch mode
      context.watch();
    } else {
      // Build once and exit if not in watch mode
      context.rebuild().then((result) => {
        context.dispose();
      });
    }
  })
  .catch(() => process.exit(1));
